# Database migration job - runs before deployment
apiVersion: batch/v1
kind: Job
metadata:
  name: ide-orchestrator-migrations
  namespace: intelligence-orchestrator
  annotations:
    # Wave 1 ensures it runs AFTER ExternalSecrets (Wave 0) but BEFORE Deployment (Wave 3)
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    metadata:
      name: ide-orchestrator-migrations
    spec:
      restartPolicy: Never
      imagePullSecrets:
      - name: ghcr-pull-secret
      # 1. Pod-Level Security Context (Required for Restricted Policy)
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 2000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: migrations
        image: ghcr.io/arun4infra/ide-orchestrator:latest
        # 2. Container-Level Security Context (Required for Restricted Policy)
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        command: ["/bin/sh", "-c"]
        args: 
          - |
            echo "Starting database migrations..."
            cd /app
            # Note: chmod might fail if file is owned by root, but usually strictly 
            # restricted images already have permissions set. We try anyway.
            chmod +x ./scripts/ci/run-migrations.sh || true
            ./scripts/ci/run-migrations.sh
            echo "Migrations completed successfully"
        envFrom:
        - secretRef:
            name: ide-orchestrator-db-conn
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
  backoffLimit: 3
  activeDeadlineSeconds: 600